### ISSUE TITLE
Building in a docker container with only python 3.6 fails

### ISSUE THREAD

**Issue by jeking3** [boostorg/python#227]
I am attempting to build all of boost using a docker container that only has Python 3.6 in it, and Boost.Python fails to build:
```
gcc.compile.c++ bin.v2/libs/python/build/gcc-7.3/release/threading-multi/list.o
In file included from ./boost/python/detail/prefix.hpp:13:0,
                 from ./boost/python/list.hpp:8,
                 from libs/python/src/list.cpp:5:
./boost/python/detail/wrap_python.hpp:50:11: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
           ^~~~~~~~~~~~
compilation terminated.

    "/usr/bin/g++-7"   -fPIC -m64 -pthread -O3 -finline-functions -Wno-inline -Wall  -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE -DNDEBUG  -I"." -I"/usr/include/python2.7" -c -o "bin.v2/libs/python/build/gcc-7.3/release/threading-multi/list.o" "libs/python/src/list.cpp"

...failed gcc.compile.c++ bin.v2/libs/python/build/gcc-7.3/release/threading-multi/list.o...
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.3/release/threading-multi/split.o
gcc.link.dll bin.v2/libs/program_options/build/gcc-7.3/release/threading-multi/libboost_program_options.so.1.69.0
common.copy stage/lib/libboost_program_options.so.1.69.0
...failed updating 1 target...
...updated 393 targets...
boost@87988c84883a:/boost$ find / -name pyconfig.h
/usr/include/x86_64-linux-gnu/python3.6m/pyconfig.h
/usr/include/python3.6m/pyconfig.h
```

The docker container can be found at:

https://github.com/boostorg/boost/pull/184
Using "docker/run.sh ubuntu bionic"

Is this repository compatible with a python 3.6-only environment (no 2.7) from boost jam builds?

**Comment by jeking3** [comment]
If I install python2.7-dev into the container it seems to resolve the issue, but should that be required?

**Comment by stefanseefeld** [comment]
Boost.Python should work with Python 3.6. I see two problems with the above:
* `b2` doesn't correctly detect Python (or at least, some of the corresponding variables, such as the include path)
* `b2` attempts to build Boost.Python nonetheless

Both of these issues are (arguably) Boost.Build bugs, and thus should be reported there.

**Comment by jeking3** [comment]
I cannot build libs/python/test with this workaround but I can build boost from the top level.
