### ISSUE TITLE
Boost.Python doesn't build under MSVC...

### ISSUE THREAD

**Issue by pdimov** [boostorg/python#420]
... with the following error:

```
compile-c-c++ bin.v2\libs\python\build\msvc-14.2\debug\address-model-32\link-static\python-3.7\threading-multi\errors.obj
errors.cpp
D:\a\boost_install\boost-root\boost/config/assert_cxx03.hpp(24): fatal error C1189: #error:  "Your compiler appears not to be fully C++03 compliant.  Detected via defect macro BOOST_NO_COMPLETE_VALUE_INITIALIZATION."
```

**Comment by pdimov** [comment]
Possibly caused by https://github.com/boostorg/conversion/commit/2598281d102932d3bdc81d48d1f2e3db49cc1872.

**Comment by stefanseefeld** [comment]
I don't have access to that platform / compiler so I can't investigate this myself, unfortunately. It sounds like we are actually requiring (some) C++11 features that this MSVC version doesn't support.

**Comment by Turim** [comment]
Please, try it out for msvc-14.3? - it builds well

**Comment by pdimov** [comment]
Seems to have been fixed on the Conversion side.
